/** Canonical audit action strings for auth / identity events. */
export const AuditAction = {
  LOGIN_SUCCESS: 'auth.login.success',
  LOGIN_FAILURE: 'auth.login.failure',
  REFRESH: 'auth.refresh',
  LOGOUT: 'auth.logout',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  ROLE_CREATE: 'role.create',
  ROLE_UPDATE: 'role.update',
  ROLE_DELETE: 'role.delete',
  ROLE_ASSIGN: 'role.assign',
  ROLE_REMOVE: 'role.remove',
  API_KEY_CREATE: 'api-key.create',
  API_KEY_REVOKE: 'api-key.revoke',
  PLUGIN_ENABLE: 'plugin.enable',
  PLUGIN_DISABLE: 'plugin.disable',
  PLUGIN_CONFIGURE: 'plugin.configure',
  WAREHOUSE_CREATE: 'warehouse.create',
  WAREHOUSE_UPDATE: 'warehouse.update',
  WAREHOUSE_DELETE: 'warehouse.delete',
  FULFILLMENT_SHIP: 'fulfillment.ship',
  RETURN_CREATE: 'return.create',
  RETURN_REFUND: 'return.refund',
  BULK_PRODUCT_UPDATE: 'bulk.product.update',
  BULK_INVENTORY_ADJUST: 'bulk.inventory.adjust',
} as const;

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];
